Add Lookup API integration for user details
SRCF/lightbluetent pull request #38
Opened 2020-08-17 23:08 UTC by matiasilva

* Adds a util for fetching data from Lookup based on a CRSid
* Implements this in the soc registration form

Touches on #2 but to fully implement this, we need to add better methods for querying a list. We can choose to use the full SDK provided by UIS.

2020-09-15 18:07 UTC, CHTJonas requested changes
Nice work! Just a few little suggestions left inline - could also use a rebase on top of the most recent `master`.

2020-09-15 18:07 UTC, CHTJonas commented on lightbluetent/utils.py
> +    res = requests.get(url, params={'fetch', "email,departingEmail"}, timeout=(0.5, 10))
```suggestion
    res = requests.get(url, params={"fetch": "email,departingEmail", "format": "json"}, timeout=(0.5, 10))
```

2020-09-15 18:07 UTC, CHTJonas commented on lightbluetent/templates/home/register.html
> +    <input name=name id="name" value="{% if user_data %} user_data.visibleName {% endif %}" required><br />
```suggestion
    <input name=name id="name" value="{% if user_data %} user_data["visibleName"] {% endif %}" required><br />
```

2020-09-15 18:07 UTC, CHTJonas commented on lightbluetent/templates/home/register.html
> +    <input name=email_address id="email_address" value="{% if user_data %} user_data.attributes[0]["value"] {% endif %}" required><br />
```suggestion
    <input name=email_address id="email_address" value="{% if user_data %} user_data["attributes"][0]["value"] {% endif %}" required><br />
```

2020-09-15 18:15 UTC, matiasilva commented on lightbluetent/utils.py
> +    res = requests.get(url, params={'fetch', "email,departingEmail"}, timeout=(0.5, 10))
Fixed!

2020-09-15 18:15 UTC, matiasilva commented on lightbluetent/templates/home/register.html
> +    <input name=name id="name" value="{% if user_data %} user_data.visibleName {% endif %}" required><br />
Darn JavaScript habits..

2020-09-18 07:13 UTC, doismellburning approved these changes
Looks good - as you say, I think it would benefit from SDK integration with (presumably) better error handling etc. but looks like it does the job nicely

2020-09-26 18:05 UTC, matiasilva commented
Closed in favor of #87.

2020-09-26 18:05 UTC, closed without merging